import pandas as pd
from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.lib import colors
import matplotlib.pyplot as plt
from reportlab.platypus import Image
from reportlab.lib.styles import getSampleStyleSheet

BASE_DIR = Path(__file__).resolve().parents[2]

df = pd.read_excel(BASE_DIR / "output" / "company_ranking.xlsx")
profit_df = pd.read_excel(BASE_DIR / "data" / "raw" / "profitandloss.xlsx")
cashflow_df = pd.read_excel(BASE_DIR / "data" / "raw" / "cashflow.xlsx")
balance_df = pd.read_excel(BASE_DIR / "data" / "raw" / "balancesheet.xlsx")

output_folder = BASE_DIR / "reports" / "tearsheets"
output_folder.mkdir(parents=True, exist_ok=True)
chart_folder = BASE_DIR / "reports" / "charts"
chart_folder.mkdir(parents=True, exist_ok=True)

styles = getSampleStyleSheet()
def get_rating(score):
    if score >= 90:
        return "Excellent", colors.darkgreen
    elif score >= 75:
        return "Very Good", colors.green
    elif score >= 60:
        return "Good", colors.orange
    else:
        return "Needs Improvement", colors.red
def generate_insights(row):
    insights = []

    if row["profit_margin"] >= 20:
        insights.append("✓ Strong profit margin indicates efficient operations.")
    else:
        insights.append("⚠ Profit margin is below the preferred level.")

    if row["debt_equity"] <= 0.5:
        insights.append("✓ Healthy debt-equity ratio with low leverage.")
    else:
        insights.append("⚠ High debt-equity ratio may increase financial risk.")

    if row["eps_growth"] > 0:
        insights.append("✓ Positive EPS growth reflects improving earnings.")
    else:
        insights.append("⚠ Negative EPS growth needs further analysis.")

    if row["distress_signal"] == "No":
        insights.append("✓ No financial distress signal detected.")
    else:
        insights.append("⚠ Financial distress signal detected.")

    return insights
for _, row in df.iterrows():

    pdf_file = output_folder / f"{row['company_name']}_tearsheet.pdf"

    doc = SimpleDocTemplate(str(pdf_file))

    elements = []

    elements.append(Paragraph("<b>N100 FINANCIAL INTELLIGENCE PLATFORM</b>", styles["Title"]))
    elements.append(Paragraph(f"<b>Company:</b> {row['company_name']}", styles["Heading2"]))
    rating, rating_color = get_rating(row["overall_score"])

    rating_table = Table([
    ["Overall Score", f"{row['overall_score']:.2f}"],
    ["Rating", rating]
    ], colWidths=[180, 180])

    rating_table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightblue),
    ("BACKGROUND", (0,1), (0,1), colors.lightgrey),
    ("BACKGROUND", (1,1), (1,1), rating_color),
    ("TEXTCOLOR", (1,1), (1,1), colors.white),
    ("GRID", (0,0), (-1,-1), 1, colors.black),
    ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),
    ("ALIGN", (0,0), (-1,-1), "CENTER"),
    ]))

    elements.append(rating_table)

    kpi_data = [
    ["Rank", row["rank"]],
    ["Overall Score", f"{row['overall_score']:.2f}"],
    ["CFO Quality", row["cfo_quality_label"]],
    ["Profit Margin", f"{row['profit_margin']:.2f}%"],
    ["Operating Margin", f"{row['operating_margin']:.2f}%"],
    ["EPS Growth", f"{row['eps_growth']:.2f}%"],
    ["Debt/Equity", f"{row['debt_equity']:.2f}"],
    ["Asset Utilization", f"{row['asset_utilization']:.2f}"],
    ["CFO/PAT Ratio", f"{row['cfo_pat_ratio']:.2f}"],
    ["Capex Intensity", f"{row['capex_intensity']:.2f}"],
    ["Distress Signal", row["distress_signal"]],
    ["Deleveraging", row["deleveraging_flag"]],
]

    

    table = Table(kpi_data, colWidths=[220, 140])

    table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,-1), colors.whitesmoke),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
    ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
    ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#E3F2FD")),
    ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ("TOPPADDING", (0,0), (-1,-1), 8),
]))

    elements.append(table)
    elements.append(
    Paragraph(
        "<br/><font size='9' color='grey'>Generated by N100 Financial Intelligence Platform</font>",
        styles["Normal"]
    )
)
    company_id = row["company_id"]

    company_profit = (
    profit_df[profit_df["company_id"] == company_id]
    .sort_values("year")
)

    plt.figure(figsize=(6, 3))

    plt.plot(
    company_profit["year"],
    company_profit["sales"],
    marker="o",
    label="Sales",
)

    plt.plot(
    company_profit["year"],
    company_profit["net_profit"],
    marker="o",
    label="Net Profit",
)

    plt.title(f"{row['company_name']} - Sales vs Net Profit")
    plt.xlabel("Year")
    plt.ylabel("Amount")
    plt.grid(True)
    plt.legend()

    chart_path = chart_folder / f"{company_id}_sales_profit.png"

    plt.savefig(chart_path, dpi=150, bbox_inches="tight")
    plt.close()

    elements.append(Image(str(chart_path), width=420, height=220))
    # ---------------- Cash Flow Chart ----------------

    company_cash = (
    cashflow_df[cashflow_df["company_id"] == company_id]
    .sort_values("year")
)

    plt.figure(figsize=(6, 3))

    plt.plot(
    company_cash["year"],
    company_cash["operating_activity"],
    marker="o",
    label="Operating"
)

    plt.plot(
    company_cash["year"],
    company_cash["investing_activity"],
    marker="o",
    label="Investing"
)

    plt.plot(
    company_cash["year"],
    company_cash["financing_activity"],
    marker="o",
    label="Financing"
)

    plt.title(f"{row['company_name']} - Cash Flow")
    plt.xlabel("Year")
    plt.ylabel("Amount")
    plt.grid(True)
    plt.legend()

    cash_chart = chart_folder / f"{company_id}_cashflow.png"

    plt.savefig(cash_chart, dpi=150, bbox_inches="tight")
    plt.close()

    elements.append(Image(str(cash_chart), width=420, height=220))
    
        # ---------------- Balance Sheet Chart ----------------

    company_balance = (
    balance_df[balance_df["company_id"] == company_id]
    .sort_values("year")
)

    plt.figure(figsize=(6, 3))

    plt.plot(
    company_balance["year"],
    company_balance["equity_capital"],
    marker="o",
    label="Equity"
)

    plt.plot(
    company_balance["year"],
    company_balance["borrowings"],
    marker="o",
    label="Borrowings"
)

    plt.plot(
    company_balance["year"],
    company_balance["total_assets"],
    marker="o",
    label="Assets"
)

    plt.title(f"{row['company_name']} - Balance Sheet")
    plt.xlabel("Year")
    plt.ylabel("Amount")
    plt.grid(True)
    plt.legend()

    balance_chart = chart_folder / f"{company_id}_balance.png"

    plt.savefig(balance_chart, dpi=150, bbox_inches="tight")
    plt.close()


    elements.append(Image(str(balance_chart), width=420, height=220))
    elements.append(Paragraph("<br/><b>AI Financial Insights</b>", styles["Heading2"]))

for insight in generate_insights(row):
    elements.append(
        Paragraph(
            f"• {insight}",
            styles["Normal"]
        )
    )

    doc.build(elements)

print(f"Generated {len(df)} company tearsheets successfully.")
